### ISSUE TITLE
Unable to play embedded dailymotion video

### ISSUE THREAD

**Issue by HelgaSokolova** [react-native-video/react-native-video#2250]
# Bug

I'm going to play an embedded dailymotion video with following url.
`https://www.dailymotion.com/embed/video/x2p99yn`
And, I get following error.
```{"error": {"code": -11850, "domain": "AVFoundationErrorDomain", "localizedDescription": "Operation Stopped", "localizedFailureReason": "The server is not correctly configured.", "localizedRecoverySuggestion": ""}, "target": 2577}```

## Platform

Which player are you experiencing the problem on:
* iOS

## Environment info

React native info output:

```bash
System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 165.95 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 16, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2, 30.0.0, 30.0.1, 30.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: 22.0.6917172-beta1
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 5.1.0-alpha8

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

`https://www.dailymotion.com/embed/video/x2p99yn`

**Comment by imavipatel** [comment]
Do you solved this problem?

**Comment by imavipatel** [comment]
> # Bug
> I'm going to play an embedded dailymotion video with following url.
> `https://www.dailymotion.com/embed/video/x2p99yn`
> And, I get following error.
> `{"error": {"code": -11850, "domain": "AVFoundationErrorDomain", "localizedDescription": "Operation Stopped", "localizedFailureReason": "The server is not correctly configured.", "localizedRecoverySuggestion": ""}, "target": 2577}`
> 
> ## Platform
> Which player are you experiencing the problem on:
> 
> * iOS
> 
> ## Environment info
> React native info output:
> 
> ```shell
> System:
>     OS: macOS 11.1
>     CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
>     Memory: 165.95 MB / 32.00 GB
>     Shell: 5.8 - /bin/zsh
>   Binaries:
>     Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
>     Yarn: 1.22.10 - /usr/local/bin/yarn
>     npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.10.0 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
>     Android SDK:
>       API Levels: 16, 22, 23, 24, 25, 26, 27, 28, 29, 30
>       Build Tools: 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.2, 30.0.0, 30.0.1, 30.0.2
>       System Images: android-19 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
>       Android NDK: 22.0.6917172-beta1
>   IDEs:
>     Android Studio: 4.1 AI-201.8743.12.41.6953283
>     Xcode: 12.2/12B45b - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_212 - /usr/bin/javac
>     Python: 2.7.16 - /usr/bin/python
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 16.13.1 => 16.13.1 
>     react-native: 0.63.3 => 0.63.3 
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found
> ```
> 
> Library version: 5.1.0-alpha8
> 
> ## Steps To Reproduce
> 
> ...
> 
> ## Expected behaviour
> 
> ## Reproducible sample code
> ## Video sample
> If possible, include a link to the video that has the problem that can be streamed or downloaded from.
> 
> `https://www.dailymotion.com/embed/video/x2p99yn`

Do you solved this problem?

**Comment by chj-damon** [comment]
I'm facing the same problem. Have you fixed it?

**Comment by reactProjects7** [comment]
im also facing same issue

**Comment by dushmantha** [comment]
I'm facing the same issue. has anyone fixed this issue, 
```
code: -11850
domain: "AVFoundationErrorDomain"
localizedDescription: "Operation Stopped"
localizedFailureReason: "The server is not correctly configured."
localizedRecoverySuggestion: ""
```

**Comment by gulsher7** [comment]
@dushmantha i think we must include mime type during upload the video on server. Some video don't play if video mimeType not defined that's why its give to us error "The server is not correctly configured." I personally realised this behaviour. 

-------For example----------
when you uploading video on server than you must include video name and its type.

    videoData.append("file", {
      uri: url,
      name: 'video name',
      type: 'video/mp4'. -->>> you must include here video format
    })

**Comment by dushmantha** [comment]
@gulsher7 Thanks for reply, It is good to know when video play from by our server. However I am trying to play video `youtube` and `vimeo` do you have any idea about that?

**Comment by BadtzMaru** [comment]
> @dushmantha i think we must include mime type during uploading the video on server. Some video don't play if video mimeType not defined that's why its give to us error "The server is not correctly configured." I personally realised this behaviour.
> 
> -------For example----------
> when you uploading video on server than you must include video name and its type.
> 
> ```
> videoData.append("file", {
>   uri: url,
>   name: 'video name',
>   type: 'video/mp4'. -->>> you must include here video format
> })
> ```

I tried this. Add type and name to the source, but it doesn't work well. also error with {"error": {"code": -11850, "domain": "AVFoundationErrorDomain", "localizedDescription": "操作停止", "localizedFailureReason": "服务器配置不正确。", "localizedRecoverySuggestion": ""}, "target": 3515}

**Comment by melero2000** [comment]
> > @dushmantha i think we must include mime type during uploading the video on server. Some video don't play if video mimeType not defined that's why its give to us error "The server is not correctly configured." I personally realised this behaviour.
> > -------For example----------
> > when you uploading video on server than you must include video name and its type.
> > ```
> > videoData.append("file", {
> >   uri: url,
> >   name: 'video name',
> >   type: 'video/mp4'. -->>> you must include here video format
> > })
> > ```
> 
> I tried this. Add type and name to the source, but it doesn't work well. also error with {"error": {"code": -11850, "domain": "AVFoundationErrorDomain", "localizedDescription": "操作停止", "localizedFailureReason": "服务器配置不正确。", "localizedRecoverySuggestion": ""}, "target": 3515}

Same error for me, could you solve it?

**Comment by mattgle** [comment]
Hi guys I've found a workaround, this might not work for everyone but still I'm posting it for the ones that need this urgent.

The thing is that like @Sanglepp said "Seems that iOS doesn't play videos that have Content-Dispositon: "attachment" header." so I decided to download the file locally and then pass that local video to the <Video/> component.

This approach worked for my because I have small videos on repeat (like "gifs") so I didn't have any problems downloading those videos and then showing them.

I've created a hook using rn-fetch-blob that downloads the video and returns the path where is located.

import { useEffect, useState } from 'react';
import RNFetchBlob from 'rn-fetch-blob';

function useFileDownload(uri) {
  const [path, setPath] = useState(null);
  useEffect(() => {
    RNFetchBlob.config({
      fileCache: true,
      appendExt: 'mp4',
    })
      .fetch('GET', uri)
      .then(res => {
        setPath(res.path());
      });
  }, []);

  if (path) {
    return path;
  }
}

export default useFileDownload;
and then I call that hook to get the working uri like this:

  const newUrl = useFileDownload(url);
  ...
        <Video
        repeat
        onLoad={hideSpinner}
        resizeMode="cover"
        source={{ uri: newUrl }}
        style={{ ...styles.image, height: 165, width: 165 }}
      />

**Comment by BadtzMaru** [comment]
> > > @dushmantha i think we must include mime type during uploading the video on server. Some video don't play if video mimeType not defined that's why its give to us error "The server is not correctly configured." I personally realised this behaviour.
> > > -------For example----------
> > > when you uploading video on server than you must include video name and its type.
> > > ```
> > > videoData.append("file", {
> > >   uri: url,
> > >   name: 'video name',
> > >   type: 'video/mp4'. -->>> you must include here video format
> > > })
> > > ```
> > 
> > 
> > I tried this. Add type and name to the source, but it doesn't work well. also error with {"error": {"code": -11850, "domain": "AVFoundationErrorDomain", "localizedDescription": "操作停止", "localizedFailureReason": "服务器配置不正确。", "localizedRecoverySuggestion": ""}, "target": 3515}
> 
> Same error for me, could you solve it?

I solved this problem. May you could ask your company's Back-end developments to config the resumable upload or download!

**Comment by indrajeet1629** [comment]
> I solved this problem. May you could ask your company's Back-end developments to config the resumable upload or download!

@BadtzMaru Could you explain how does this help?

**Comment by freeboub** [comment]
This is a feature request. It  an be implemented using JS webview api

https://developers.dailymotion.com/player/#player-embed-script
