### ISSUE TITLE
only audio and black screen on both emulators for iso and android

### ISSUE THREAD

**Issue by ivan-vilches-5** [react-native-video/react-native-video#3172]
## Platform
Which player are you experiencing the problem on:
* iOS
* Android

## Environment info

npx react-native info         
info Fetching system and libraries information...
System:
  OS: macOS 13.4
  CPU: (8) arm64 Apple M1
  Memory: 72.91 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.4.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.7.2
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.07.03.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/ivanvilches/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 34.0.0
    System Images:
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /opt/homebrew/opt/openjdk@11/bin/javac
  Ruby:
    version: 3.2.1
    path: /Users/ivanvilches/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.2
    wanted: 0.72.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

## Steps To Reproduce

when i run the project using npx react-native start then i open the emulator for ios and android, in both i can only listen the audio but the video player is on **Black**
...

## Expected behaviour
Watch the video

## Reproducible sample code

my code is 
`import React, { useRef } from 'react';
import { SafeAreaView, StatusBar, useColorScheme, StyleSheet } from 'react-native';
import Video from 'react-native-video';
import { Colors } from 'react-native/Libraries/NewAppScreen';

interface BufferInfo {
  isBuffering: boolean;
}

interface VideoError {
  error: {
    code: number;
    domain: string;
  };
}

const App = () => {
  const isDarkMode = useColorScheme() === 'dark';
  const player = useRef(null);

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  const onBuffer = (bufferInfo: BufferInfo) => {
    console.log("Buffering:", bufferInfo);
  };

  const videoError = (error: VideoError) => {
    console.log("Video error:", error);
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <Video 
         source={{uri: "https://live.forstreet.cl/live/livestream.m3u8"}} 
         ref={player} 
         onBuffer={onBuffer} 
         onError={videoError} 
         style={styles.backgroundVideo} 
         controls 
         pictureInPicture={false} 
       
      />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  backgroundVideo: {
    width: '100%',
    height: 300,
    // backgroundColor: 'black', // Agregamos un color de fondo
  },
});

export default App;
`

## Video sample
https://www.loom.com/share/415f6e6ef3de41a4bd895ec8cdbbac65

**Comment by chandanmaurya0** [comment]
Try removing android:hardwareAccelerated="false" from AndroidManifest.xml file

**Comment by TDUser91** [comment]
I'm having kind of the same issue here video ***DRM protected content***, but in my case I get a ***black screen AND no audio*** but I can retrieve video data, I can see the progress bar move properly. 

In the rare where it works is that, is when: I put two Video components on the screen, I refreshed the app (still got black srcreen and no audio), then remove one of the Video Components and refresh again (here the video and audio play correcly). If I refresh again it stops working again.

here are my logs:
```
npx react-native info
info Fetching system and libraries information...
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 4.79 GB / 15.40 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.2.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.0 - ~/Bureau/TD_repo/multiplatform_application_vialis/node_modules/.bin/npm
    Watchman: 20230430.125247.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 31, 33, 34
      Build Tools: 30.0.3, 33.0.0, 34.0.0
      System Images: android-34 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
  npmGlobalPackages:
    *react-native*: Not Found
```

My code sample: 

```
import React, { useRef, useState, useEffect } from "react";
import { View, Text, TouchableOpacity, StyleSheet } from "react-native";
import Video, { DRMSettings, DRMType } from "react-native-video";
import VideoPlayer from 'react-native-media-console';

const VideoPlayerView = () => {

    const drmSettings: DRMSettings = {
        type: DRMType.WIDEVINE,
        licenseServer: "https://cwip-shaka-proxy.appspot.com/no_auth",
    };

    return (
        <View>
            <Text style={{ textAlign: 'center' }}>
                Demo Video Player
            </Text>

            {/*  TRY ADDING THIS, refresh, then remove and refresh again
             <View style={{ backgroundColor: "red", height: 300 }}>
                <Text>
                    VideoPlayer Component
                </Text>

                <VideoPlayer
                    style={styles.backgroundVideoPlayer}
                    source={{ uri: "https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd" }}
                    controls={true}
                    paused={false}
                    onLoad={(onLoadData) => { console.log('VIDEO_PLAYER: ' + onLoadData) }}
                    navigator={null}
                    drm={drmSettings}
                />

            </View>  */}

            <View style={{ backgroundColor: "blue", height: 300 }}>
                <Text>
                    Video Component
                </Text>
                <TouchableOpacity>
                    <Video
                        style={styles.backgroundVideo}
                        source={{ uri: "https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd" }}
                        controls={true}
                        paused={false}
                        onLoad={function (onLoadData) {
                            console.log('Video Component onLoadData: ', onLoadData);
                        }}
                        drm={drmSettings}
                        onReadyForDisplay={() => {
                            console.log('onReadyForDisplay')
                        }}
                    />
                </TouchableOpacity>
            </View>
        </View >
    );
}

const styles = StyleSheet.create({
    backgroundVideo: {
        height: 250,
        position: 'relative',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
    },

    backgroundVideoPlayer: {
        height: 250,
        width: 250,
        backgroundColor: 'red',
        position: 'relative',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
    },
});
export default VideoPlayerView;
```

**Comment by freeboub** [comment]
Just try this url on V6.0.0 version, on androidTV emulator, I don't have any issue.
Are you able to reproduce the issue on V6 ?

**Comment by alokgahlot** [comment]
I am facing the same issue of black screen for my local video

How should i solve it ?
